### PR TITLE
Migrated code to TensorFlow v2

### PR DESCRIPTION
**Pull request by seidnerj**
with some additional tidying up for the code styling/language.

### CODE REVIEW

**Comment by seidnerj** [comment]
Can this please be merged? Thanks.

**Comment by zhangqianhui** [comment]
I will check it. Thanks.

**Comment by seidnerj** [comment]
👍

**Comment by zhangqianhui** [comment]
I need to check. Wait

**Comment by seidnerj** [comment]
👍

**Comment by seidnerj** [comment]
Should I close this?

**Pull request closed without merging**
